export const PERSONAL = {
  name: "Muhammad Abrar Ahmad",
  initials: "MAA",
  title: "Full Stack Developer",
  sub: "& Cyber Security Enthusiast",
  email: "abrarjr66@gmail.com",
  linkedin: "linkedin.com/in/muhammad-abrar-ahmad",
  github: "github.com/abrar",
  location: "Rawalpindi, Pakistan",
  university: "NUST — Military College of Signals",
  bio: "NUST student crafting <strong>scalable full-stack systems</strong> and solving real-world problems. Previously built production features at <strong>Dr Coderz</strong>, Wimbel & Four Minds. Passionate about clean architecture, agile development, and continuous learning.",
  tagline: "Crafting digital experiences that fuse logic and design into living, breathing products.",
};

export const STATS = [
  { num: "4", suffix: "+", label: "Internships" },
  { num: "5", suffix: "+", label: "Projects Shipped" },
  { num: "12", suffix: "+", label: "Technologies" },
  { num: "1", suffix: "st", label: "Class at NUST MCS" },
];

export const SKILLS = {
  Frontend: ["React", "Next.js", "TypeScript", "JavaScript", "Tailwind CSS", "HTML5", "CSS3", "Redux", "Zustand", "Shadcn UI"],
  Backend:  ["Node.js", "Express", "NestJS", "Django", "Flask", "GraphQL", "REST API", "JWT"],
  Database: ["MongoDB", "PostgreSQL", "MySQL", "TypeORM", "Mongoose"],
  DevOps:   ["Docker", "AWS", "Vercel", "Netlify", "Git", "CI/CD", "Figma", "Jest", "Postman", "Java"],
};

export const PROJECTS = [
  {
    id: "01",
    name: "ApexTrader",
    desc: "A real-time virtual cryptocurrency trading platform integrating live market data via CoinGecko and Binance WebSocket streams, rendering interactive candlestick price analysis charts and simulated portfolio tracking.",
    tags: ["React.js", "TypeScript", "TailwindCSS", "Chart.js", "WebSockets"],
    color: "#ff3d00",
    github: "https://github.com/abrar898/ApexTrader",
    live: "https://apextrader-demo.vercel.app",
  },
  {
    id: "02",
    name: "AutiConnect",
    desc: "A high-performance, WCAG 2.1-compliant accessibility platform engineered for neurodiverse users, featuring a custom component library built with atomic design principles and full screen-reader compatibility.",
    tags: ["React.js", "TypeScript", "TailwindCSS", "Vite", "Accessibility"],
    color: "#c8a84b",
    github: "https://github.com/abrar898/AutiConnect",
    live: "https://autoconnect-demo.vercel.app",
  },
  {
    id: "03",
    name: "StoreBase",
    desc: "Production-grade, self-hosted cloud storage platform with drag-and-drop uploads, nested folder hierarchy, in-browser media previews, time-limited share links, and optimized multi-stage file processing.",
    tags: ["Next.js 14", "Node.js", "Express.js", "MongoDB", "TailwindCSS", "Zustand"],
    color: "#10b981",
    github: "https://github.com/abrar898/StoreBase",
    live: "https://storebase-demo.vercel.app",
  },
  {
    id: "04",
    name: "MedConnect",
    desc: "Full-stack healthcare platform featuring WebRTC-powered video consultations, real-time Socket.io signaling, secure medical record management, and an AI-powered semantic search engine for medical reports.",
    tags: ["MongoDB", "Express.js", "React.js", "Node.js", "WebRTC", "Socket.io"],
    color: "#00d4ff",
    github: "https://github.com/abrar898/MedConnect",
    live: "https://medconnect-demo.vercel.app",
  },
  {
    id: "05",
    name: "Cloud-Deployed Text Classification System",
    desc: "High-performance text classification SVM model built from scratch in Python. Achieved 90.34% accuracy on the IMDb dataset, deployed as a production-grade FastAPI inference microservice.",
    tags: ["Python", "scikit-learn", "SVM", "FastAPI", "NumPy", "joblib"],
    color: "#8b5cf6",
    github: "https://github.com/abrar898/Text-Classification-SVM",
  },
  {
    id: "06",
    name: "RAG Chat PDF",
    desc: "Retrieval-Augmented Generation (RAG) system enabling natural language Q&A over PDF documents using FAISS indexing, OpenAI embeddings, and persistent caching to eliminate redundant API cost.",
    tags: ["Python", "LangChain", "OpenAI", "FAISS", "Streamlit"],
    color: "#ec4899",
    github: "https://github.com/abrar898/RAG-Chat-PDF",
  },
  {
    id: "07",
    name: "Converge",
    desc: "A real-time collaborative document editor utilizing Django Channels and Yjs CRDT for automatic conflict resolution, featuring offline persistence and Django REST Framework access controls.",
    tags: ["Django 5", "Django Channels", "WebSockets", "Yjs CRDT", "React 18", "TypeScript"],
    color: "#3b82f6",
    github: "https://github.com/abrar898/Converge",
  },
  {
    id: "08",
    name: "Music Streaming & Event Management Platform",
    desc: "Scalable streaming platform and event system with tiered seating, featuring a high-throughput QR code ticketing pipeline designed to handle 10,000+ concurrent check-ins.",
    tags: ["Django 4", "PostgreSQL", "JavaScript", "TailwindCSS", "RBAC", "QR Code"],
    color: "#f59e0b",
    github: "https://github.com/abrar898/Music-Event-Platform",
  },
  {
    id: "09",
    name: "Product Catalog & E-Commerce Checkout System",
    desc: "Modular e-commerce catalog and checkout engine featuring structured RBAC, persistent session management, and automated itemized PDF invoice generation.",
    tags: ["Django 4", "PostgreSQL", "JavaScript", "TailwindCSS", "ReportLab", "RBAC"],
    color: "#ef4444",
    github: "https://github.com/abrar898/Ecommerce-Checkout",
  },
];

export const EXPERIENCE = [
  {
    company: "Dr Coderz",
    role: "Full-Stack Developer Intern",
    period: "Aug 2025 – Nov 2025",
    location: "Remote",
    current: false,
    color: "#ff3d00",
    tags: ["Next.js", "NestJS", "TypeScript", "GraphQL", "PostgreSQL", "MongoDB", "Docker"],
    points: [
      "Delivered end-to-end full-stack features across three production platforms (E-Commerce, Edu-Learning, Job-Application) using React/TypeScript frontends and Node.js/Express backend microservices.",
      "Designed and implemented 20+ RESTful API endpoints with JWT-based authentication, input validation, and role-based access control (RBAC), ensuring secure and scalable service communication.",
      "Developed production-grade applications using Next.js 14 (SSR/SSG) and NestJS with modular, domain-driven architecture, improving code maintainability and horizontal scalability.",
      "Integrated PostgreSQL (TypeORM) and MongoDB (Mongoose) for hybrid relational/document data persistence, optimising query performance and schema design across distributed services.",
    ],
  },
  {
    company: "Four Minds",
    role: "Software Developer Intern",
    period: "May – Aug 2025",
    location: "Remote",
    current: false,
    color: "#00d4ff",
    tags: ["React Native", "Firebase", "React", "Node.js", "State Management"],
    points: [
      "Built a cross-platform React Native weather app with Firebase real-time data and auth.",
      "Applied advanced state management and navigation systems across devices.",
      "Collaborated on full-stack features with React and Node.js.",
    ],
  },
  {
    company: "Wimbel",
    role: "Frontend Developer",
    period: "Apr 2025 – Jun 2025",
    location: "Remote",
    current: false,
    color: "#10b981",
    tags: ["React.js", "TypeScript", "REST APIs", "Hooks", "Responsive UI"],
    points: [
      "Engineered a modular, component-driven POS frontend using React.js and TypeScript, implementing reusable UI components and custom hooks that reduced code duplication by 40% and accelerated feature delivery cycles.",
      "Architected responsive inventory management dashboards with real-time stock updates, sales analytics summaries, and role-based access views differentiated for admin and cashier personas.",
      "Consumed and integrated RESTful APIs for product lifecycle management, transaction processing, and receipt generation; implemented optimistic UI updates achieving sub-100ms perceived latency.",
    ],
  },
  {
    company: "Tech Horizon",
    role: "Web Developer Intern",
    period: "Aug – Sep 2025",
    location: "Remote",
    current: false,
    color: "#c8a84b",
    tags: ["MERN Stack", "Next.js", "React", "Node.js", "Express", "MongoDB"],
    points: [
      "Developed a dynamic MERN application with SSR using Next.js and React.",
      "Implemented RESTful APIs and integrated MongoDB for scalable data storage.",
      "Ensured responsive, cross-browser compatible design across all devices.",
    ],
  },
  {
    company: "Disruptive AI",
    role: "Full-Stack Developer Intern",
    period: "Aug – Oct 2024",
    location: "Islamabad, Pakistan",
    current: false,
    color: "#8b5cf6",
    tags: ["React", "Node.js", "Express", "JavaScript", "Git", "Unit Testing"],
    points: [
      "Developed, tested, and deployed scalable web apps with React and Node.js/Express.",
      "Implemented full-stack features following Agile workflows and unit testing principles.",
      "Used Git/GitHub for version control and CI/CD readiness.",
    ],
  },
];

export const NAV = [
  { label: "About",      href: "#about" },
  { label: "Skills",     href: "#skills" },
  { label: "Projects",   href: "#projects" },
  { label: "Experience", href: "#experience" },
  { label: "Contact",    href: "#contact" },
];
